services:
  postgres:
    image: postgres:16-alpine
    container_name: music-tracker-db
    environment:
      POSTGRES_DB: music_tracker
      POSTGRES_USER: music_tracker_user
      POSTGRES_PASSWORD: music_tracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music_tracker_user -d music_tracker"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
